# Generated by Django 4.0.2 on 2022-04-01 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TrophyAndEffect', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTrophy',
            new_name='UserEffect',
        ),
    ]
