# Generated by Django 4.0.2 on 2022-09-12 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TrophyAndEffect', '0001_initial'),
        ('GroupPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportuser',
            name='reported_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user_reported_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportuser',
            name='reporter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user_reporter_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaderboardplayers',
            name='leaderboard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupPortal.leaderboard'),
        ),
        migrations.AddField(
            model_name='leaderboardplayers',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='winner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrophyAndEffect.effect'),
        ),
        migrations.AddField(
            model_name='chat',
            name='leaderboard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupPortal.leaderboard'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
