# Generated by Django 4.0.2 on 2022-04-04 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TrophyAndEffect', '0002_rename_usertrophy_usereffect'),
        ('GroupPortal', '0003_leaderboard_trophy_collected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('message', models.CharField(max_length=250)),
                ('chat_effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrophyAndEffect.effect')),
                ('leaderboard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupPortal.leaderboard')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
