# Generated by Django 4.0.2 on 2022-04-11 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GroupPortal', '0004_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateField()),
                ('leaderbaord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupPortal.leaderboard')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user_reported_user', to=settings.AUTH_USER_MODEL)),
                ('reporter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user_reporter_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
