# Generated by Django 4.0.2 on 2022-03-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='is_broken',
            field=models.BooleanField(),
        ),
    ]
