# Generated by Django 4.0.2 on 2022-03-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_alter_chain_is_broken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chain',
            old_name='started_date',
            new_name='collected_date',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='is_broken',
        ),
    ]
