# Generated by Django 4.0.2 on 2022-03-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0003_rename_started_date_chain_collected_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chain',
            name='user_id',
        ),
    ]
