# Generated by Django 4.0.2 on 2022-04-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_pg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
