# Generated by Django 4.0.2 on 2022-09-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_id', models.IntegerField()),
                ('completed_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FitnessTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_id', models.IntegerField()),
                ('completed_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ImplementTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implement_id', models.IntegerField()),
                ('completed_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RandomTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('priority', models.CharField(max_length=10)),
                ('taskType', models.CharField(max_length=20)),
                ('taskMinute', models.IntegerField(blank=True, null=True)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('restMinute', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.IntegerField()),
                ('completed_date', models.DateField()),
            ],
        ),
    ]
