# Generated by Django 4.0.2 on 2022-03-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_domain_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='user_id',
        ),
    ]
