# Generated by Django 4.0.2 on 2022-03-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_domain_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='photo_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
