# Generated by Django 4.0.2 on 2022-03-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_alter_domain_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='user_id',
        ),
    ]
