# Generated by Django 4.0.2 on 2022-03-18 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain', '0007_domain_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='percentage',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='domain',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
