# Generated by Django 4.0.2 on 2022-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_domain_percentage_alter_domain_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='percentage',
            field=models.CharField(default='25', max_length=5),
        ),
    ]
