name: digi3map
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.2.0
  smooth_page_indicator: ^1.0.0+2
  audioplayers: ^0.20.1
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+8
  shared_preferences: ^2.0.13
  http: ^0.13.4
  google_sign_in: ^5.2.4
  flutter_facebook_auth: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/icons/

  fonts:
    - family: TwCen
      fonts:
        - asset: assets/fonts/TwCenBold.otf
        - asset: assets/fonts/TwCenMtRegular.otf
    - family: Segoesc
      fonts:
        - asset: assets/fonts/segoesc.ttf


