name: digi3map
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.2.0
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/

  fonts:
    - family: TwCenBold
      fonts:
        - asset: assets/fonts/TwCenBold.otf
        - asset: assets/fonts/TwCenMtRegular.otf
    - family: Segoesc
      fonts:
        - asset: assets/fonts/segoesc.ttf


