# Generated by Django 4.0.2 on 2022-09-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('remark', models.CharField(max_length=100)),
                ('dateCollected', models.DateField()),
            ],
        ),
    ]
