# Generated by Django 4.0.2 on 2022-03-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.ImageField(upload_to='images/')),
                ('widget_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('progress', models.IntegerField(default=0)),
                ('domain_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='domain.domain')),
            ],
        ),
    ]
