# Generated by Django 4.0.2 on 2022-09-12 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.ImageField(upload_to='images/')),
                ('widget_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('progress', models.IntegerField(default=0)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('rest', models.IntegerField(blank=True, null=True)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.domain')),
            ],
        ),
        migrations.CreateModel(
            name='HabitTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField()),
                ('habitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.habit')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
