# Generated by Django 4.0.2 on 2022-04-09 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_remove_domain_percentage_domain_points'),
        ('habit', '0002_habit_rest_habit_sets_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='domain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.domain'),
        ),
        migrations.CreateModel(
            name='HabitTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField()),
                ('habitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.habit')),
            ],
        ),
    ]
