# Generated by Django 4.0.2 on 2022-03-16 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_domain_user_id'),
        ('habit', '0003_alter_habit_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='domain_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='domain.domain'),
        ),
    ]
