# Generated by Django 4.0.2 on 2022-03-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_habit_domain_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user_id',
        ),
    ]
