# Generated by Django 4.0.2 on 2022-03-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0006_habit_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='photo_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
