# Generated by Django 4.0.2 on 2022-03-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0007_alter_habit_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user_id',
        ),
    ]
